package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"api/graph/model"
	"context"
	"fmt"
)

// Extract is the resolver for the extract field.
func (r *queryResolver) Extract(ctx context.Context, userID *int, tipoDocumento *int, dataComeco *string, dataFinal *string) (*model.Contagem, error) {
	panic(fmt.Errorf("not implemented: Extract - extract"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id *int, segment *string) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
