FROM node:latest
WORKDIR /dashboard
COPY /front/ /

COPY /db/substituteEnvVars.sh /
RUN chmod +x ../substituteEnvVars.sh

RUN npm i
RUN npm i -g @angular/cli

EXPOSE 4200
ENTRYPOINT ["../substituteEnvVars.sh"]
CMD ["ng", "serve", "-c=production"]
