// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Count struct {
	Name  string `json:"name"`
	Value int    `json:"value"`
}

type Extract struct {
	ID             string `json:"id"`
	CreatedAt      string `json:"created_at"`
	PagesProcessed int    `json:"pages_processed"`
	DocType        string `json:"doc_type"`
	UserID         int    `json:"user_id"`
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Segment string `json:"segment"`
}
