// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contagem struct {
	Count int `json:"count"`
}

type User struct {
	ID      string  `json:"id"`
	Name    *string `json:"name,omitempty"`
	Segment *string `json:"segment,omitempty"`
}
