// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Count struct {
	Name  string `json:"name"`
	Value int    `json:"value"`
}

type User struct {
	ID      string `json:"id"`
	Name    string `json:"name"`
	Segment string `json:"segment"`
}
