on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - run: |
          cd back
          go test ./service
          go test ./graph
    
